global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rails_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['rails_exporter:9394']
        labels:
          instance: 'vm-rails-exporter'
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    params:
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - netdev
        - filesystem
        - loadavg
        - vmstat
        - systemd